global:
  scrape_interval: 0.2s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['localhost:9100']

scrape_configs:
- job_name: redis
  static_configs:
  - targets:
    - 'localhost:9121'
    - 'localhost:9122'
    - 'localhost:9123'
    - 'localhost:9124'
    - 'localhost:9125'
    - 'localhost:9126'
