global:
  scrape_interval: 500ms

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['localhost:9100']
- job_name: redis
  scrape_interval: 200ms
  static_configs:
  - targets:
    - 'localhost:9121'
    - 'localhost:9122'
    - 'localhost:9123'
    - 'localhost:9124'
    - 'localhost:9125'
    - 'localhost:9126'
