data_dir = "/home/usada/infra/data0/vector/data"

[api]
enabled = true

[sources.redis]
type = "file"
include = [ "/home/usada/infra/data0/redis/*/*.log" ]

[sinks.openobserve]
type = "http"
inputs = [ "redis" ]
uri = "http://localhost:5080/api/default/redis-log/_json"
method = "post"
auth.strategy = "basic"
auth.user = "root@example.com"
auth.password = "ComplexPass#123"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false
